name: scrape-dividends

on:
  workflow_dispatch:
    inputs:
      ticker:
        description: "Stock ticker (e.g., 2330)"
        required: true
        default: "2330"
  schedule:
    - cron: "0 18 * * 1" # 每週一 18:00 UTC 自動跑一次（可刪）

permissions:
  contents: write

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node 20
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install deps
        run: |
          npm i
          npx playwright install --with-deps chromium

      - name: Scrape
        env:
          TICKER: ${{ github.event.inputs.ticker || '2330' }}
        run: node api/scrape.js

      - name: Commit JSON
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: update dividends JSON"
          file_pattern: data/*.json
